(() => {
  'use strict';

  const storageKey = 'dangle.session.v1';
  const oldStorageKey = 'offlineai.session.v1';
  // Compatibility marker for the updater shipped before the DANGLE redesign.
  // The old updater checks the downloaded UI for this legacy control name.
  const legacyUiValidationMarker = 'clearTopButton';
  void legacyUiValidationMarker;
  const text = value => String(value ?? '');
  const escapeHtml = value => text(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const state = { phase:'BOOT', intensity:.2, targetIntensity:.2, currentId:null, chats:[], messages:[], pending:false, config:{ apiBase:'', configPath:'/api/config', healthPath:'/api/health', chatPath:'/api/chat', parameters:{temperature:.2,topP:.9,maxOutputTokens:384,maxContextTokens:2048,retrievalLimit:5,thinking:true} } };
  const els = {};
  const mountPrefix = String(window.OFFLINEAI_BASE || '').replace(/\/$/, '');
  const endpoint = path => `${state.config.apiBase || mountPrefix}${path}`;

  function brand() { return '<span class="brand"><span class="dan">DAN</span><span class="gle">GLE</span><span class="usb-trace" aria-hidden="true"></span></span>'; }
  function cacheElements() { ['app','boot','dataField','legacyLogo','legacyFallback','shards','bootBrand','homeBrand','miniBrand','sidebar','openSidebar','closeSidebar','newChat','historyList','historyCount','globalSettings','globalPanel','aiControls','aiPanel','composer','prompt','sendButton','composerStatus','chatMessages','chatTitle','errorBox','modelSelect','contextSelect','retrievalLimit','thinkingToggle','libraryToggle','temperature','topP','maxOutputTokens','modelFolder','serviceStatus','engineLabel','versionBadge','checkUpdatesButton','applyUpdateButton','restartButton','debugButton','debugCopyButton','clearButton','updateStatus','debugOutput','systemPrompt','modelList','refreshModelButton','downloadModelButton','modelDownloadStatus'].forEach(id => { els[id] = document.getElementById(id); }); }
  function request(url, options = {}) { return fetch(url, { cache:'no-store', signal:AbortSignal.timeout(190000), ...options, headers:{'Content-Type':'application/json', ...(options.headers || {})} }).then(async response => { let body={}; try { body=await response.json(); } catch (_) {} if (!response.ok) throw new Error(body.error || `Service returned HTTP ${response.status}`); return body; }); }
  function showError(message) { els.errorBox.textContent=message || ''; els.errorBox.hidden=!message; }
  function setStatus(label, kind='') { els.serviceStatus.className=`service-line ${kind}`; els.serviceStatus.querySelector('span').textContent=label; }
  function save() { const current=state.chats.find(chat=>chat.id===state.currentId); if(current){current.messages=state.messages.filter(item=>!item.pending); current.updatedAt=Date.now();} localStorage.setItem(storageKey,JSON.stringify({chats:state.chats})); }
  function loadHistory() { try { const saved=JSON.parse(localStorage.getItem(storageKey)||'{}'); state.chats=Array.isArray(saved.chats)?saved.chats:[]; } catch (_) { state.chats=[]; } if(!state.chats.length){ try { const old=JSON.parse(localStorage.getItem(oldStorageKey)||'[]'); if(Array.isArray(old)&&old.length) state.chats=[{id:`chat-${Date.now()}`,title:old.find(m=>m.role==='user')?.content?.slice(0,52)||'Recovered conversation',messages:old,updatedAt:Date.now()}]; } catch (_) {} } state.chats.sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0)); renderHistory(); }
  function renderHistory() { els.historyList.innerHTML=''; if(!state.chats.length) els.historyList.innerHTML='<div class="history-empty">No conversations yet.<br>Your local archive will appear here.</div>'; state.chats.forEach(chat=>{const row=document.createElement('div');row.className=`history-row ${chat.id===state.currentId?'active':''}`;row.innerHTML=`<button class="history-open" data-open="${escapeHtml(chat.id)}" title="Open conversation">${escapeHtml(chat.title||'Untitled conversation')}</button><span class="history-menu"><button data-rename="${escapeHtml(chat.id)}" aria-label="Rename conversation" title="Rename">✎</button><button data-delete="${escapeHtml(chat.id)}" aria-label="Delete conversation" title="Delete">×</button></span>`;els.historyList.appendChild(row);}); els.historyCount.textContent=`${state.chats.length} conversation${state.chats.length===1?'':'s'}`; }
  function setPhase(phase) { state.phase=phase; els.app.dataset.state=phase; state.targetIntensity=phase==='BOOT'?.35:phase==='HOME_IDLE'?.2:phase==='CHAT_IDLE'?.5:1; }
  function openChat(chat) { state.currentId=chat.id;state.messages=Array.isArray(chat.messages)?chat.messages:[];els.sidebar.classList.remove('open');setPhase('CHAT_IDLE');render();renderHistory(); }
  function newChat() { state.currentId=null;state.messages=[];els.sidebar.classList.add('open');setPhase('HOME_IDLE');showError('');render();renderHistory();els.prompt.focus(); }
  function createChat(message) { const chat={id:`chat-${Date.now()}-${Math.random().toString(16).slice(2)}`,title:message.slice(0,52),messages:[],updatedAt:Date.now()};state.chats.unshift(chat);state.currentId=chat.id;return chat; }
  function inlineMarkdown(value) { return escapeHtml(value).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>'); }
  function renderMarkdown(value) { const lines=text(value).split(/\r?\n/);const output=[];let list=null,code=false,codeLines=[];const close=()=>{if(list){output.push(`</${list}>`);list=null;}};lines.forEach(line=>{if(line.trim().startsWith('```')){if(code){output.push(`<pre><code>${escapeHtml(codeLines.join('\n'))}</code></pre>`);codeLines=[];code=false;}else{close();code=true;}return;}if(code){codeLines.push(line);return;}if(!line.trim()){close();return;}const h=line.match(/^(#{1,6})\s+(.+)$/);if(h){close();output.push(`<h${h[1].length}>${inlineMarkdown(h[2])}</h${h[1].length}>`);return;}const li=line.match(/^\s*[-*+]\s+(.+)$/);if(li){if(list!=='ul'){close();output.push('<ul>');list='ul';}output.push(`<li>${inlineMarkdown(li[1])}</li>`);return;}const quote=line.match(/^\s*>\s?(.+)$/);if(quote){close();output.push(`<blockquote>${inlineMarkdown(quote[1])}</blockquote>`);return;}close();output.push(`<p>${inlineMarkdown(line)}</p>`);});if(code)output.push(`<pre><code>${escapeHtml(codeLines.join('\n'))}</code></pre>`);close();return output.join(''); }
  function performanceLabel(value) { if(!value)return '';const parts=[];if(Number(value.tokens_per_second)>0)parts.push(`${Number(value.tokens_per_second).toFixed(1)} tokens/s`);if(Number(value.elapsed_seconds)>0)parts.push(`${Number(value.elapsed_seconds).toFixed(1)}s`);return parts.length?`Performance · ${parts.join(' · ')}`:''; }
  function contextLabel(value) { if(!value)return '';const used=Number(value.estimated_used_tokens||0),max=Number(value.configured_context_limit||0);return max?`Context · ${used.toLocaleString()} / ${max.toLocaleString()} tokens (${Math.round(Number(value.percentage||0))}%)`:''; }
  function render() { els.homeBrand.innerHTML=brand();els.miniBrand.innerHTML=brand();els.chatMessages.innerHTML='';els.chatTitle.textContent=state.currentId?(state.chats.find(c=>c.id===state.currentId)?.title||'CONVERSATION'):'';state.messages.forEach(message=>{const node=document.createElement('article');node.className=`message ${message.role}${message.pending?' pending':''}`;node.innerHTML=`<div class="message-label">${message.role==='user'?'YOU':'DANGLE'}</div><div class="message-content">${message.role==='assistant'&&!message.pending?renderMarkdown(message.content):`<p>${escapeHtml(message.content)}</p>`}</div>`;if(message.role==='assistant'&&!message.pending){const meta=document.createElement('div');meta.className='message-meta';meta.textContent=message.searchPerformed?'Library search performed':`Library search skipped${message.retrievalReason?`: ${message.retrievalReason}`:''}`;node.appendChild(meta);if(message.context){const context=document.createElement('div');context.className='message-meta';context.textContent=contextLabel(message.context);node.appendChild(context);}if(message.reasoning){const details=document.createElement('details');details.className='thinking-block';details.innerHTML=`<summary>Show thinking</summary><div class="thinking-content">${renderMarkdown(message.reasoning)}</div>`;node.appendChild(details);}if(message.performance){const perf=document.createElement('div');perf.className='message-meta';perf.textContent=performanceLabel(message.performance);node.appendChild(perf);}}if(message.sources?.length){const details=document.createElement('details');details.className='sources';details.innerHTML=`<summary>${message.sources.length} source${message.sources.length===1?'':'s'}</summary>`+message.sources.map(source=>{const path=source.relative_path||source.path||'';const page=Number(source.pdf_page);const hash=Number.isFinite(page)&&page>0?`#page=${page}`:'';return `<div class="source"><div class="source-title"><a class="source-link" href="${endpoint('/api/source')}?path=${encodeURIComponent(path)}${hash}" target="_blank" rel="noreferrer">Open PDF</a>${escapeHtml(source.title||source.source_filename||path||'Local document')} ${source.pdf_page?`p. ${escapeHtml(source.pdf_page)}`:''}</div><div class="source-path">${escapeHtml(path)}</div><div class="source-text">${escapeHtml(source.snippet||source.text||'')}</div></div>`;}).join('');node.appendChild(details);}els.chatMessages.appendChild(node);});els.chatMessages.lastElementChild?.scrollIntoView({block:'nearest'}); }
  function currentParameters() { return {temperature:Number(els.temperature.value),topP:Number(els.topP.value),maxOutputTokens:Number(els.maxOutputTokens.value),maxContextTokens:Number(els.contextSelect.value),retrievalLimit:Number(els.retrievalLimit.value),thinking:els.thinkingToggle.checked}; }
  function applyConfig(config) { state.config={...state.config,...config};const p={...state.config.parameters,...(config.parameters||{})};els.temperature.value=p.temperature??.2;els.topP.value=p.topP??.9;els.maxOutputTokens.value=p.maxOutputTokens??384;els.contextSelect.value=p.maxContextTokens??2048;els.retrievalLimit.value=p.retrievalLimit??5;els.thinkingToggle.checked=p.thinking!==false;const models=config.models||config.localModels||[];els.modelSelect.innerHTML=models.map(model=>`<option value="${escapeHtml(typeof model==='string'?model:model.id)}">${escapeHtml(typeof model==='string'?model:(model.label||model.id))}</option>`).join('');if(config.active_model)els.modelSelect.value=config.active_model;els.modelFolder.textContent=config.folder?`Model folder: ${config.folder}`:'';els.engineLabel.textContent=config.engine||'';els.versionBadge.textContent=config.version?`DANGLE v${config.version}`:'';els.systemPrompt.textContent=config.system_prompt||config.systemPrompt||'Loaded locally.'; }
  async function loadConfig() { try{applyConfig(await request('config.json',{headers:{}}));}catch(_){}try{applyConfig(await request(endpoint(state.config.configPath)));}catch(_){}loadModelManager(); }
  async function health() { try{const value=await request(endpoint(state.config.healthPath||'/api/health'));setStatus('LOCAL SERVICE ONLINE','good');els.engineLabel.textContent=value.engine||state.config.engine||'';if(value.database)els.modelFolder.textContent=`Catalog: ${value.database}`;return value;}catch(error){setStatus('LOCAL SERVICE OFFLINE','bad');showError(error.message);return null;} }
  async function submit(event) { event.preventDefault();if(state.pending)return;const content=els.prompt.value.trim();if(!content)return;showError('');if(!state.currentId)createChat(content);els.sidebar.classList.remove('open');setPhase('GENERATING');state.messages.push({role:'user',content});els.prompt.value='';resizePrompt();const pending={role:'assistant',content:'Working locally…',pending:true};state.messages.push(pending);state.pending=true;els.sendButton.disabled=true;els.composerStatus.textContent='GENERATING';render();try{const body=await request(endpoint(state.config.chatPath||'/api/chat'),{method:'POST',body:JSON.stringify({message:content,model:els.modelSelect.value||undefined,thinking:els.thinkingToggle.checked,searchLibrary:els.libraryToggle.checked,parameters:currentParameters(),history:state.messages.slice(0,-2).filter(item=>!item.pending).map(item=>({role:item.role,content:item.content}))})});pending.content=body.answer||body.message||'The service returned no answer.';pending.pending=false;pending.reasoning=body.reasoning||'';pending.sources=body.sources||[];pending.searchPerformed=body.searchPerformed??body.retrieval?.performed??pending.sources.length>0;pending.retrievalReason=body.retrieval?.reason||body.context?.skip_reason||'';pending.performance=body.performance||null;pending.context=body.context||body.context_accounting||null;setPhase('CHAT_IDLE');els.composerStatus.textContent='';save();render();renderHistory();}catch(error){state.messages.pop();setPhase('CHAT_IDLE');showError(`Could not reach the local assistant. ${error.message}`);els.composerStatus.textContent='';render();}finally{state.pending=false;els.sendButton.disabled=false;els.prompt.focus();save();} }
  function resizePrompt(){els.prompt.style.height='auto';els.prompt.style.height=`${Math.min(130,Math.max(42,els.prompt.scrollHeight))}px`;}
  async function checkUpdates(){els.updateStatus.textContent='Checking GitHub update manifest…';try{const result=await request(endpoint('/api/update/check'));els.updateStatus.textContent=result.message||(result.updateAvailable?`Version ${result.latestVersion} is available.`:'Already up to date.');els.applyUpdateButton.hidden=!result.updateAvailable;}catch(error){els.updateStatus.textContent=`Update check failed: ${error.message}`;}}
  async function applyUpdate(){els.applyUpdateButton.disabled=true;els.updateStatus.textContent='Downloading and installing…';try{const result=await request(endpoint('/api/update/apply'),{method:'POST',body:'{}'});els.updateStatus.textContent=result.message||'Update installed.';els.applyUpdateButton.hidden=true;if(result.restartRequired)els.restartButton.hidden=false;}catch(error){els.updateStatus.textContent=`Update failed: ${error.message}`;}finally{els.applyUpdateButton.disabled=false;}}
  async function restart(){els.restartButton.disabled=true;els.updateStatus.textContent='Restarting Dangle in this tab…';try{await request(endpoint('/api/restart'),{method:'POST',body:'{}'});let attempts=0;while(attempts++<195){await new Promise(resolve=>setTimeout(resolve,1000));try{const value=await request(endpoint('/api/health'),{signal:AbortSignal.timeout(3000)});if(value.ok){els.updateStatus.textContent='Dangle restarted.';window.location.reload();return;}}catch(_){}}throw new Error('The updated service did not become ready.');}catch(error){els.restartButton.disabled=false;els.updateStatus.textContent=`Restart failed: ${error.message}`;}}
  async function runDebug(){els.debugOutput.hidden=false;els.debugOutput.textContent='Running local diagnostic…';try{const value=await request(endpoint('/api/debug'));els.debugOutput.textContent=value.summary||JSON.stringify(value,null,2);}catch(error){els.debugOutput.textContent=`Diagnostic failed: ${error.message}`;}}
  async function loadModelManager(){if(!els.modelList)return;try{const value=await request(endpoint('/api/models/manage'));const models=value.models||[];els.modelList.innerHTML=models.map(model=>`<div class="model-row"><span>${escapeHtml(model.label||model.id)}<small>${model.available?' · available':' · not found'}</small></span>${model.active?'':'<button data-remove-model="'+escapeHtml(model.id)+'" type="button">Delete</button>'}</div>`).join('')||'<p class="panel-note">No managed models reported.</p>';}catch(error){els.modelList.innerHTML=`<p class="panel-note">${escapeHtml(error.message)}</p>`;}}
  async function downloadModel(){els.modelDownloadStatus.textContent='Preparing model download…';els.downloadModelButton.disabled=true;try{await request(endpoint('/api/model/download'),{method:'POST',body:'{}'});els.modelDownloadStatus.textContent='Download started. This can take a while.';}catch(error){els.modelDownloadStatus.textContent=error.message;}finally{els.downloadModelButton.disabled=false;}}
  async function deleteModel(id){if(!window.confirm(`Delete ${id} from local storage?`))return;try{await request(endpoint('/api/models/delete'),{method:'POST',body:JSON.stringify({model:id})});loadModelManager();}catch(error){els.modelDownloadStatus.textContent=error.message;}}
  function clearConversation(){if(!state.currentId)return newChat();state.chats=state.chats.filter(chat=>chat.id!==state.currentId);save();newChat();}
  function boot(){for(let i=0;i<28;i++){const node=document.createElement('i');node.className='shard';node.style.left=`${24+Math.random()*52}%`;node.style.top=`${28+Math.random()*38}%`;node.style.setProperty('--x',`${(Math.random()-.5)*520}px`);node.style.setProperty('--y',`${(Math.random()-.5)*330}px`);node.style.setProperty('--r',`${(Math.random()-.5)*920}deg`);node.style.setProperty('--delay',`${Math.random()*180}ms`);els.shards.appendChild(node);}els.bootBrand.innerHTML=`${brand()}<div class="boot-tagline">Offline intelligence. Knowledge that survives.</div>`;setTimeout(()=>els.legacyLogo.classList.add('destroy'),1250);setTimeout(()=>els.boot.classList.add('destroying','black'),1850);setTimeout(()=>els.boot.classList.add('resolve'),2750);setTimeout(()=>{els.boot.classList.add('done');els.app.style.opacity='1';setPhase('HOME_IDLE');els.sidebar.classList.toggle('open',state.chats.length>0);els.prompt.focus();},4300);}
  function createDataField(){const canvas=els.dataField,ctx=canvas.getContext('2d',{alpha:true});let width=0,height=0,dpr=1,particles=[],last=0,quality=1,frames=0,frameClock=performance.now();const resize=()=>{dpr=Math.min(2,window.devicePixelRatio||1);width=window.innerWidth;height=window.innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);};const seed=()=>{particles=Array.from({length:Math.round((26+34*state.intensity)*quality)},()=>({x:Math.random()*width,y:Math.random()*height,speed:.1+Math.random()*.55,length:8+Math.random()*34,alpha:.035+Math.random()*.16,red:Math.random()<.08,glyph:Math.random().toString(16).slice(2,6).toUpperCase()}));};const draw=now=>{requestAnimationFrame(draw);if(document.hidden||now-last<33)return;const elapsed=last?now-last:16.67;last=now;const delta=Math.min(50,elapsed)/16.67;state.intensity+=(state.targetIntensity-state.intensity)*.035;const intensity=state.intensity;ctx.clearRect(0,0,width,height);ctx.globalCompositeOperation='lighter';particles.forEach(p=>{p.y+=p.speed*(.6+intensity*2.4)*delta;p.x+=Math.sin(now/1800+p.y/210)*.12*intensity;if(p.y>height+70){p.y=-30;p.x=Math.random()*width;}const alpha=p.alpha*(.25+intensity*.72);ctx.strokeStyle=p.red?`rgba(229,45,57,${alpha})`:`rgba(244,244,241,${alpha*.42})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+p.length*(.55+intensity));ctx.stroke();if(intensity>.75){ctx.font='9px ui-monospace,monospace';ctx.fillStyle=p.red?`rgba(229,45,57,${alpha})`:`rgba(244,244,241,${alpha*.7})`;ctx.fillText(p.glyph,p.x+3,p.y+10);}});ctx.globalCompositeOperation='source-over';frames++;if(now-frameClock>1800){const fps=frames*1000/(now-frameClock);if(fps<22&&quality>.55){quality-=.15;seed();}else if(fps>48&&quality<1){quality+=.1;seed();}frames=0;frameClock=now;}};window.addEventListener('resize',()=>{resize();seed();});resize();seed();requestAnimationFrame(draw);}
  function bind(){els.globalSettings.addEventListener('click',()=>{const open=els.globalPanel.hidden;els.globalPanel.hidden=!open;els.globalSettings.setAttribute('aria-expanded',String(open));els.aiPanel.hidden=true;});els.aiControls.addEventListener('click',()=>{const open=els.aiPanel.hidden;els.aiPanel.hidden=!open;els.aiControls.setAttribute('aria-expanded',String(open));els.globalPanel.hidden=true;});document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>{els[button.dataset.close].hidden=true;}));document.addEventListener('click',event=>{if(!event.target.closest('.popover')&&!event.target.closest('#aiControls')&&!event.target.closest('#globalSettings')){els.aiPanel.hidden=true;els.globalPanel.hidden=true;}});els.openSidebar.addEventListener('click',()=>els.sidebar.classList.add('open'));els.closeSidebar.addEventListener('click',()=>els.sidebar.classList.remove('open'));els.newChat.addEventListener('click',newChat);els.historyList.addEventListener('click',event=>{const open=event.target.closest('[data-open]'),rename=event.target.closest('[data-rename]'),del=event.target.closest('[data-delete]');if(open){const chat=state.chats.find(item=>item.id===open.dataset.open);if(chat)openChat(chat);}else if(rename){const chat=state.chats.find(item=>item.id===rename.dataset.rename),name=window.prompt('Conversation name',chat?.title||'');if(chat&&name?.trim()){chat.title=name.trim().slice(0,80);save();renderHistory();}}else if(del&&window.confirm('Delete this conversation from this device?')){state.chats=state.chats.filter(item=>item.id!==del.dataset.delete);if(state.currentId===del.dataset.delete)newChat();else{save();renderHistory();}}});els.miniBrand.addEventListener('click',newChat);els.composer.addEventListener('submit',submit);els.prompt.addEventListener('input',resizePrompt);els.prompt.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();els.composer.requestSubmit();}});els.checkUpdatesButton.addEventListener('click',checkUpdates);els.applyUpdateButton.addEventListener('click',applyUpdate);els.restartButton.addEventListener('click',restart);els.debugButton.addEventListener('click',runDebug);els.clearButton.addEventListener('click',clearConversation);els.refreshModelButton?.addEventListener('click',loadModelManager);els.downloadModelButton?.addEventListener('click',downloadModel);els.modelList?.addEventListener('click',event=>{const button=event.target.closest('[data-remove-model]');if(button)deleteModel(button.dataset.removeModel);});els.debugCopyButton?.addEventListener('click',()=>navigator.clipboard?.writeText(els.debugOutput.textContent||''));}
  async function init(){cacheElements();loadHistory();bind();createDataField();loadConfig();health();boot();}
  document.addEventListener('DOMContentLoaded',init);
})();
